services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./.docker/postgres-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  api-gateway:
    build: ./backend/services/api-gateway
    env_file:
      - ./backend/services/api-gateway/.env
    ports:
      - "8080:8080"
    # volumes:
    #   - ./certs/cert.pem:/certs/cert.pem:ro
    #   - ./certs/key.pem:/certs/key.pem:ro
    depends_on:
      - auth-service
      - user-service
      - playlist-service
      - vote-service
      - realtime-service
      - music-provider-service
      - mock-service

  auth-service:
    build: ./backend/services/auth-service
    env_file:
      - ./backend/services/auth-service/.env
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

  user-service:
    build: ./backend/services/user-service
    env_file:
      - ./backend/services/user-service/.env
    ports:
      - "3005:3005"
    depends_on:
      postgres:
        condition: service_healthy

  playlist-service:
    build: ./backend/services/playlist-service
    env_file:
      - ./backend/services/playlist-service/.env
    ports:
      - "3002:3002"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  vote-service:
    build: ./backend/services/vote-service
    env_file:
      - ./backend/services/vote-service/.env
    ports:
      - "3003:3003"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  realtime-service:
    build: ./backend/services/realtime-service
    env_file:
      - ./backend/services/realtime-service/.env
    ports:
      - "3004:3004"
    depends_on:
      redis:
        condition: service_started

  music-provider-service:
    build: ./backend/services/music-provider-service
    env_file:
      - ./backend/services/music-provider-service/.env
    ports:
      - "3007:3007"
    depends_on:
      redis:
        condition: service_started

  mock-service:
    build: ./backend/services/mock-service
    # нам нужен этот порт их .env, если мы будем использовать этот сервис
    # env_file:
    #   - ./backend/services/mock-service/.env
    ports:
      - "3006:3006"

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5175:5175"
    # volumes:
    #   - ./certs/cert.pem:/certs/cert.pem:ro
    #   - ./certs/key.pem:/certs/key.pem:ro
    depends_on:
      - api-gateway
      - realtime-service

volumes:
  pgdata:
